### ISSUE TITLE
Generated testcases

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#1]
# Spec for `generators/gen.yaml`

See #50.

**Comment by TimonKnigge** [comment]
> Generators must be [...] idempotent.
What do you mean with this?

> Generators creating multiple `.in` files
This seems redundant if you implement the next point (multiple rules per `.gen` file). That would be my preference since you can also logically group testcases, e.g. `flow-killer.gen` uses `anti-flow.py` with a couple different sets of parameters.

> Possible uses are to create `.desc` files or to first generate a `.in` and then transform/modify it using a second generator.
Sometimes I use post-processing steps (like permuting all indices or randomly rotating a testcase for a geometry problem) that I'd want to apply to all testcases (independent of generator). But this is also easily achieved with a little python module that all these generators can include.

> This does imply that the basenames of different .gen files should be prefix-free.
Make sure to issue a warning during e.g. `bt generate` when this is not the case. Alternatively you can prefix all generated files with some prefix like `gen-`.

> Before running a `.gen file`, it might be necessary to build the generator. Some options:
I would just enforce that generators should be written in python, I don't see the point in using C++ for this.

> Is it reasonable to assume that all files for a single testcase will be generated? (And not, e.g. a generated `.in` but a static `.ans`.)
I'd prefer to only assume the input is generated, because otherwise we might have to write a whole solution inside the generator (possibly in a different language than the model solution).

> Do we really need to complicate things with the multiple outputs per generator setup? I'm happy to support it but don't see myself using it.
Personally I'd just require the generator to write it's testcase to `stdout` and output this in `data/secret/testcase.in`. 

> Can we still allow a single generator to write multiple .in? That's simpler to setup and would probably cover most of the usages. By using prefix-free generators we can still check which files were generated.
Maybe simpler here would be to have a format where the testcase name is written on the first line of the generator, followed by a set of generator inputs, which will be run sequentially and have their stdout piped into `${TESTNAME}-1.in`, `${TESTNAME}-2.in` etc. Then there's no prefix collision issue because we know exactly which files are being generated.

**Comment by RagnarGrootKoerkamp** [comment]
> > Generators must be [...] idempotent.
> 
> What do you mean with this?
Running the same generator twice should not change anything.

> > Generators creating multiple `.in` files
> 
> This seems redundant if you implement the next point (multiple rules per `.gen` file). That would be my preference since you can also logically group testcases, e.g. `flow-killer.gen` uses `anti-flow.py` with a couple different sets of parameters.
Hmm, interesting idea. We had already considered the case where `testcase.gen` calls a single generator that writes to `testcase-1.in`, `testcase-2.in` and `testcase-3.in`.
One way to implement this idea is to have `testcase.gen` containing
```
gen.py A
gen.py B
gen.py C
```
and `gen.py` looking like
```
arg = sys.argv[1]
file = sys.argv[2]
Pathlib(file+'-'+arg+'.in').write_text(arg)
```
where it automatically creates a suitable filename from the provided arguments.

One thing that's possible (but I don't like it), is to have `testcase.gen` as
```
gen.py A testcase-1.in
gen.py B testcsae-2.in
gen.py C testcase-3.in
```
and `gen.py`:
```
```

> > Possible uses are to create `.desc` files or to first generate a `.in` and then transform/modify it using a second generator.
> 
> Sometimes I use post-processing steps (like permuting all indices or randomly rotating a testcase for a geometry problem) that I'd want to apply to all testcases (independent of generator). But this is also easily achieved with a little python module that all these generators can include.
> 
> > This does imply that the basenames of different .gen files should be prefix-free.
> 
> Make sure to issue a warning during e.g. `bt generate` when this is not the case. Alternatively you can prefix all generated files with some prefix like `gen-`.
> 
> > Before running a `.gen file`, it might be necessary to build the generator. Some options:
> 
> I would just enforce that generators should be written in python, I don't see the point in using C++ for this.
> 
> > Is it reasonable to assume that all files for a single testcase will be generated? (And not, e.g. a generated `.in` but a static `.ans`.)
> 
> I'd prefer to only assume the input is generated, because otherwise we might have to write a whole solution inside the generator (possibly in a different language than the model solution).
> 
> > Do we really need to complicate things with the multiple outputs per generator setup? I'm happy to support it but don't see myself using it.
> 
> Personally I'd just require the generator to write it's testcase to `stdout` and output this in `data/secret/testcase.in`.
> 
> > Can we still allow a single generator to write multiple .in? That's simpler to setup and would probably cover most of the usages. By using prefix-free generators we can still check which files were generated.
> 
> Maybe simpler here would be to have a format where the testcase name is written on the first line of the generator, followed by a set of generator inputs, which will be run sequentially and have their stdout piped into `${TESTNAME}-1.in`, `${TESTNAME}-2.in` etc. Then there's no prefix collision issue because we know exactly which files are being generated.

**Comment by RagnarGrootKoerkamp** [comment]
> > Generators must be [...] idempotent.
> 
> What do you mean with this?

Running the same generator twice should not change anything.

> > Generators creating multiple `.in` files
> 
> This seems redundant if you implement the next point (multiple rules per `.gen` file). That would be my preference since you can also logically group testcases, e.g. `flow-killer.gen` uses `anti-flow.py` with a couple different sets of parameters.

Hmm, interesting idea. We had already considered the case where `testcase.gen` calls a single generator that writes to `testcase-1.in`, `testcase-2.in` and `testcase-3.in`.
One way to implement this idea is to have `testcase.gen` containing
```
gen.py A
gen.py B
gen.py C
```
and `gen.py` looking like
```
arg = sys.argv[1]
file = sys.argv[2]
Pathlib(file+'-'+arg+'.in').write_text(arg)
```
where it automatically creates a suitable filename from the provided arguments.

One thing that's possible (but I don't like it), is to have `testcase.gen` as
```
gen.py A testcase-1
gen.py B testcsae-2
gen.py C testcase-3
```
and `gen.py` similar to before. (This works because it now reads the manually
provided filename instead of the system provided filename.)

> > Possible uses are to create `.desc` files or to first generate a `.in` and then transform/modify it using a second generator.
> 
> Sometimes I use post-processing steps (like permuting all indices or randomly rotating a testcase for a geometry problem) that I'd want to apply to all testcases (independent of generator). But this is also easily achieved with a little python module that all these generators can include.

Yes, either that or just append an extra line to each generator file.
Usually these transformations apply to most but not all of the testcases so a
more general approach doesn't really work I think.


> > This does imply that the basenames of different .gen files should be prefix-free.
> 
> Make sure to issue a warning during e.g. `bt generate` when this is not the case. Alternatively you can prefix all generated files with some prefix like `gen-`.

Yes, added a TODO.
 
> > Before running a `.gen file`, it might be necessary to build the generator. Some options:
> 
> I would just enforce that generators should be written in python, I don't see the point in using C++ for this.

That works most of the time, but there have been cases where a C++ generator is
wanted. One example is where we used gnu mpz to generate high precision answers.
(Sure, that's also possible in Python, but some things are just easier in other
languages. Maybe doing the same in Python would be much slower and hence more
inconvenient.)

Jaap suggested to use a combination of 2 and 3: Build the `gen` using `build` if
available and fall back to building from `gen.cpp` or `gen.java` when possible.

> > Is it reasonable to assume that all files for a single testcase will be generated? (And not, e.g. a generated `.in` but a static `.ans`.)
> 
> I'd prefer to only assume the input is generated, because otherwise we might have to write a whole solution inside the generator (possibly in a different language than the model solution).

Well, `.ans` files can already be regenerated easily right? Either the provided
`.gen` can do this, and if it doesn't the tooling can just fall back to any
accepted solution and use that to generate the answer file.

(The only edge case that's excluded here is when you generate the `.in` but then
manually modify the `.ans` to suit your needs. That sounds unlikely to me.)

> > Do we really need to complicate things with the multiple outputs per generator setup? I'm happy to support it but don't see myself using it.
> 
> Personally I'd just require the generator to write it's testcase to `stdout` and output this in `data/secret/testcase.in`.

But then a generator can't write to multiple testcases, and that is definitely a
requirement here. For example, this is useful when there are multiple
'testcasas' per input file but at most 100 per file. You could write a single generator
that generates 1000 testcases and automatically splits them over 10 files.
This only works well if that generator can write to 10 separate files in one
run.

> > Can we still allow a single generator to write multiple .in? That's simpler to setup and would probably cover most of the usages. By using prefix-free generators we can still check which files were generated.
> 
> Maybe simpler here would be to have a format where the testcase name is written on the first line of the generator, followed by a set of generator inputs, which will be run sequentially and have their stdout piped into `${TESTNAME}-1.in`, `${TESTNAME}-2.in` etc. Then there's no prefix collision issue because we know exactly which files are being generated.

Hmm, can you expand on this? I think this conflicts with the idea of having
these 'transforming generators' that read an existing `.in` file and modify it.

Also, I'd like to prevent having the testcase names inside the file. It
would be really nice to only use the name of the `.gen` file as that allows for
super easy renaming.

**Comment by TimonKnigge** [comment]
> But then a generator can't write to multiple testcases, and that is definitely a
requirement here. For example, this is useful when there are multiple
'testcasas' per input file but at most 100 per file. You could write a single generator
that generates 1000 testcases and automatically splits them over 10 files.
This only works well if that generator can write to 10 separate files in one
run.

Why? I don't see a practical use case for this. Not only would I not want to encourage putting multiple tests in a single file, I'm not sure why you'd want to get the worst of both worlds and have a single test consist of multiple files, each with multiple testcases.

I'd personally prefer something like: `mygenerator.py` takes sysarg's for input and writes to stdout. Then you'd make a file called `mytestcase.gen` with contents:

```
mygenerator.py 1234
mygenerator.py 4321
mygenerator.py 1111
myothergenerator.py 1 2 3
```

Running this generator would result in:

```
generator.py 1234 > mytestcase-1.in
generator.py 4321 > mytestcase-2.in
generator.py 1111 > mytestcase-3.in
myothergenerator.py 1 2 3 > mytestcase-4.in
```

Note that this by default erases the previous contents of `mytestcase-X.in`.

**Comment by TimonKnigge** [comment]
Finally, it'd be nice to have some token like `$SEED`, that I can use in these `.gen` files with the expectation that it gets filled in with the same value each time the generator is run (but not the same for each occurrence of this token in the files). For example, replace the `i`th occurrence of this token with the last ten bits of the md5 hash of `i` or something like that. This way I don't have to come up with new seeds every time and I can just copy the same exact line multiple times and expect it to result in different cases each time (assuming the format I described above).

**Comment by RagnarGrootKoerkamp** [comment]
I like the idea of having a $SEED. I'd say that it's computed as a hash of the line it occurs on and the number of this $SEED within the file.

Small drawback is that $SEEDs later in the file depend on $SEEDs earlier in the file but that's fine.

**Comment by RagnarGrootKoerkamp** [comment]
> > But then a generator can't write to multiple testcases, and that is definitely a
> > requirement here. For example, this is useful when there are multiple
> > 'testcasas' per input file but at most 100 per file. You could write a single generator
> > that generates 1000 testcases and automatically splits them over 10 files.
> > This only works well if that generator can write to 10 separate files in one
> > run.
> 
> Why? I don't see a practical use case for this. Not only would I not want to encourage putting multiple tests in a single file, I'm not sure why you'd want to get the worst of both worlds and have a single test consist of multiple files, each with multiple testcases.

Well, we did this for `familyphotos` in BAPC this year,  because we had to. Can't say I like it either but would be nice to allow this.

> 
> I'd personally prefer something like: `mygenerator.py` takes sysarg's for input and writes to stdout. Then you'd make a file called `mytestcase.gen` with contents:
> 
> ```
> mygenerator.py 1234
> mygenerator.py 4321
> mygenerator.py 1111
> myothergenerator.py 1 2 3
> ```
> 
> Running this generator would result in:
> 
> ```
> generator.py 1234 > mytestcase-1.in
> generator.py 4321 > mytestcase-2.in
> generator.py 1111 > mytestcase-3.in
> myothergenerator.py 1 2 3 > mytestcase-4.in
> ```
> 
> Note that this by default erases the previous contents of `mytestcase-X.in`.

Hmm. The initial idea of `.gen` files was to have a single `.gen` file per testcase, so you would just split the 4 lines in your example over `mytestcase-1.gen`, `mytestcase-2.gen`, ....

Also, if we want to allow transformations on the input, it would look like:
```
random-graph.py $SEED 100 1000
shuflle-graph $SEED
```

That should definitely be executed as
```
random-graph.py $SEED 100 1000 testcase > testcase.in
shuffle-graph $SEED testcase > testcase.in
```
because `shuffle-graph` needs to know which `.in` file to read and has to write to the same file (not `testcase-1.in`).

(We could even do a `< testcase.in` as well for the `suffle-graph` but not sure about that yet.)

> Keep in mind - the more general and convoluted you make this feature, the less it is going to be used.

Yes. it's really about finding the right balance between simple and easy to use vs. flexible and works in all cases.

**Comment by ludopulles** [comment]
> The nth occurrence of $SEED in the .gen file will be generated as a hash of the line containing the $SEED and the number n.

This might be nasty if you remove the first test case in your generator file. You may as well use the number of times this exact command was before it, so multiple random test cases with the same command give different test cases.

**Comment by RagnarGrootKoerkamp** [comment]
> > The nth occurrence of $SEED in the .gen file will be generated as a hash of the line containing the $SEED and the number n.
> 
> This might be nasty if you remove the first test case in your generator file. You may as well use the number of times this exact command was before it, so multiple random test cases with the same command give different test cases.

Yeah, we're not doing that. It's just a hash of the current line. Let me remove all outdated discussion from the post.

**Comment by SuprDewd** [comment]
The current way of adding a dummy parameter to get a new $SEED feels a bit dirty. What about making $SEED parameterized somehow? For example by allowing parameters of the form `$SEED:str`, where `str` can be any string. The `str` part would just be ignored, and this parameter treated as a regular $SEED parameter:
```
random-1.in:    stdout.py $SEED
random-1a.in:   stdout.py $SEED   # same seed, so same test data is generated
random-2.in:    stdout.py $SEED:2 # different $SEED, because seed is parameterized by `2`
random-3.in:    stdout.py $SEED:banana # different $SEED, because seed is parameterized by `banana`
```

**Comment by RagnarGrootKoerkamp** [comment]
@SuprDewd I've updated it to only require that `$SEED` is a prefix of the argument for it to be substituted. Removed the extra `:` because it's not really necessary (but still allowed).
