### ISSUE TITLE
Add flag to `generate` to skip input_format_validators

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#105]
It would be nice if generators could run without any validators being present.

Or maybe just change the error into a warning:
```ERROR: No input_format validators found, at least one is required.```

Things seem to be broken when the data: dictionary is empty.

Ideally, `bt generate` works to generate .ans files even when `generators.yaml` only contains `solution: ...` and nothing else. Even better would be to automatically pick a solution and not need a generators.yaml at all.

**Comment by mjdv** [comment]
I run into this problem in the following situation: I only want to write .in files and have .ans files automatically generated using any submission from /submissions/accepted. It would be nice if, from a clean directory, the command `bt generate` simply did this, without having to edit any configuration files. There are the following barriers:

1. This process should go through with no more than a warning if I/O validators are missing; or, if there is an error, there should be a flag to override the error.
2. This process should go through with no more than a warning if I/O validators are present but violated; or, if there is an error, there should be a flag to override the error.
3. This process should go through without explicitly choosing a submission in a configuration file. It could pick any submission, the alphabetically first, or the oldest submission by default.
4. This process should (as much as possible) not depend on test cases being listed in a configuration file.

Ideally, you never have to touch a configuration file until you need one of the following features:

1. Generated test cases.
2. A specific submission used for generating `.ans` files.
3. (Others?)

**Comment by RagnarGrootKoerkamp** [comment]
I think #111 implements all of the above. The only difference:
- It picks a **random** solution from `submissions/accepted`, instead of 'the first' one, to slightly encourage creating a generators.yaml. When passing `--default_solution`, a hint is printed on how to do this, which I hope should be sufficient.
