### ISSUE TITLE
Optimize parsing in `validation.h`

### ISSUE THREAD

**Issue by mpsijm** [RagnarGrootKoerkamp/BAPCtools#153]
Interactive problems seem to have struggles with parsing a lot of integers.

**Comment by RagnarGrootKoerkamp** [comment]
Ways to speed this up:

- In `get_string`, make `std::string s` static or a class member, so that it's allocation is reused.
- Instead of `stoll`, use `std::from_chars`, which is made for speed and locale independent (which is good). This needs c++17 though, and we may not want to use c++17...

**Comment by mpsijm** [comment]
> This needs c++17 though, and we may not want to use c++17...

Do you mean "at most c++17" or "at least c++17"? I think the latter case is acceptable, even LTS distributions should include that nowadays. It was C++20 that we had trouble with :stuck_out_tongue:

**Comment by RagnarGrootKoerkamp** [comment]
I meant that we may want to stick with c++14, but you're right, it was `contains` from cpp20 that was an issue. In that case it's c++17 all the way :D
