### ISSUE TITLE
improve `pdf -w`

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#167]
When doing `bt pdf -w`, it should print a message every time compilation is started and finished. (Ideally overwriting the line; maybe using the existing bar class.)

When there are errors, these should be shown as well.

Maybe it's also possible to make zathura auto refresh contents, because currently it doesn't see through the symlink and needs a manual refresh.

**Comment by mpsijm** [comment]
Additionally, `bt pdf -w` is not yet compatible with `--cp`, because the LaTeX process never finishes.

All of this could be fixed if the watching is done from Python rather than using LaTeX's built-in watcher.

**Comment by RagnarGrootKoerkamp** [comment]
We should also add a `-o/--open` flag to open the pdf, or maybe even something more clever like checking if it's already open and only open if not.
