### ISSUE TITLE
Find duplicate testcases

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#174]
problemtools does it, and so should

**Comment by mzuenni** [comment]
Related to #135 ?

**Comment by RagnarGrootKoerkamp** [comment]
This is to report about duplicated testcases in `data/secret`. I'll update the other issue as well.

**Comment by mzuenni** [comment]
doesn't `bt validate` already check for duplicate test cases? However, unlike the validity of the test case, this is not checked by `bt generate`. `bt generate` could call the `bt validate` method or is this not done for performance reasons?

**Comment by RagnarGrootKoerkamp** [comment]
yeah `bt validate` does this so we're good. I don't do it while generating for simplicity I suppose.
