### ISSUE TITLE
Input Validator/Testdata checks

### ISSUE THREAD

**Issue by mzuenni** [RagnarGrootKoerkamp/BAPCtools#187]
Problemtools does some sanity checks on the input validator. A validator should (normally) reject the following:

- An empty file
- Binary file/non-printable characters
- Random text file
- A valid test case with duplicated spaces
- A valid test case with duplicated newlines
- A leading zero before an integer (could be ok)
- Garbage added behind a valid test case

Additionally, we could check the test cases:

- All files should have the same line endings
- All whitespace should be space/newline

This might be a good feature to add.

**Comment by RagnarGrootKoerkamp** [comment]
I think this would be nice to have. It's just not high enough on my own priority list that I'll ever implement it myself I think.

If you write using the `validation.h`, most of these checks are automatic anyway.

I already have support for tests in `data/bad/`, which could possibly be reused for this. Adding some on-the-fly generated bad testcases when checking for actual files there is probably sufficient.
