### ISSUE TITLE
Compact submission/testcase overview

### ISSUE THREAD

**Issue by mzuenni** [RagnarGrootKoerkamp/BAPCtools#195]
I would like to add a compact overview of all submission/testcases to the `bt run` command (similar to what domjudge displays).
It could look something like this:
![example](https://user-images.githubusercontent.com/19410663/158419468-08c90e97-0fb2-4d95-bc4e-620329436f4e.png)
Right now it first prints all testcases with an id and then displays a table with the verdicts. (A for AC, T for TLE, R for RTE and W for WA)

some thoughts about this
- less terminal pollution than -v but also less information
- the table could need some more tweaking (split samples and secret testcases, make the mapping from column to testcase clearer)

what do other think about this?

**Comment by RagnarGrootKoerkamp** [comment]
@mpsijm @ludopulles wdyt?

I don't like the printing of the list of testcases so much. Could also do that separately in `bt list-testcases` or so.

I'd like it a lot if the table was rendered incrementally.

What if the number of testcases is larger than terminal width?

Numbering should continue from sample to secret, but could have a column of | in between

**Comment by mpsijm** [comment]
Since the total number of test cases can become quite large, I don't think this should be the default. I think having `--table` flag for the `run` command is fine, because the behaviour of the command doesn't change, only the presentation. Additionally, printing the full list of test cases every time sounds like a bit much, so adding an extra command or flag to do that sounds good.

Other than that, I agree with @RagnarGrootKoerkamp :slightly_smiling_face:

**Comment by ludopulles** [comment]
For rendering it seems like the current `bt run --table` works most likely. I think adding the verdict {A,T,R,W} with same green/red coloring is a nice way to add more info to the table.
May I ask what the added benefit is for transposing the table? I think this `--table` option is already rarely used, so perhaps adding a `--transpose` flag to it might be a bit too much.

**Comment by mzuenni** [comment]
For me the transposed table would fit better on screen (especially if the row wrappes like described above) and I am using the table for different purposes i.e. I don't want to find a specific testcase but want to quickly see if the submissions fail on specific/multiple testcases. Therefore the transposed table feels more natural. Also note that the current `--table` command discards some rows since it has a different purpose

 Adding the ATRW to the current `--table` would also be nice I guess.

**Comment by RagnarGrootKoerkamp** [comment]
@mzuenni could you make a PR for this?

**Comment by mzuenni** [comment]
Yes, but right now it is always printed, we probably only draw this if a flag is passed?

**Comment by RagnarGrootKoerkamp** [comment]
hmm; it's reasonable to print it by default I think, and maybe disable it with a flag when you don't like it / the terminal doesn't support it.

**Comment by mzuenni** [comment]
It already respects `--no-bar`.  Not sure about making it default (even though I always use it myself...).
But still, there are things like "print this at most once per 0.1sec" or something like that, and i am not sure how to add this ^^'

**Comment by RagnarGrootKoerkamp** [comment]
Do we need rate limiting? It would be a bit annoying to implement is nicely
indeed.
