### ISSUE TITLE
Compile generators/validators separately from submissions

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#230]
Not sure how, but it would be nice to set compilation flags/commands for submissions only

**Comment by mzuenni** [comment]
do we even want the `--cpp-flags` for anything else then submissions?

**Comment by RagnarGrootKoerkamp** [comment]
Hmm. We used to have some flags to make sure my constraints checker compiles because it used `std::source_location`, but that's already gone
I don't really remember why exactly we needed this, and I don't think it has come up again, so I'm inclined to just close?

**Comment by mzuenni** [comment]
I mean for submissions it makes sense to ensure that AC submission pass even when `-fsanitize=address,undefined` is given.

**Comment by RagnarGrootKoerkamp** [comment]
Hmm; that's true.
One way to do this could be to allow running with `--languages_yaml ../custom-languages.yaml` that can override some of the rules with higher priority ones, so that users can specify their own custom invocations for multiple languages. That would also allow changing compiler flags, and feels more general than adding a flag per language.
Wdyt?

**Comment by mzuenni** [comment]
yea sounds good to me

**Comment by mzuenni** [comment]
ah wait, but this would again be used for submissions and generators etc.? I think the idea here was to explicitly be able to enable sanitizers for the accepted submissions?

**Comment by RagnarGrootKoerkamp** [comment]
Hmm yeah true. The flag could be specific to only override `languages.yaml` for submissions?

**Comment by mpsijm** [comment]
If the only use case here is to enable sanitizers for the submissions, why not just dynamically append those flags to the `build` command for C++ submissions? Adding the extra flag for custom `languages.yaml` settings feels to me as if we'd be adding complexity that would only be used by a few people (if they even remember it exists), but verifying that submissions pass with sanitizers enabled sounds like something that everybody could benefit from, and that doesn't need to be toggleable? (But I'm not super familiar with C++, I don't know if simply always having the sanitizers enabled for submissions could be annoying or not :stuck_out_tongue:)

**Comment by RagnarGrootKoerkamp** [comment]
We definitely do not want always on sanitizers. But a generic `--sanitize` flag that does whatever each language requires (currently only C/C++) can work.

**Comment by mzuenni** [comment]
yeah we should not enable it by default because it significantly slows down submissions. but removing the old flag and adding a new for sanitizers sounds fine
