### ISSUE TITLE
Problem PDF

### ISSUE THREAD

**Issue by mzuenni** [RagnarGrootKoerkamp/BAPCtools#243]
For the nwerc we added code to change the context pdf (see 0ce33b42757616811685e10d212f58017d00bcea). However, this does not apply to the problem pdf build for each problem individually. Unfortunately, these pdfs are displayed in the DOMjudge and in the zip which is pretty inconsistent... (see [nwerc problems zip](https://commissies.ch.tudelft.nl/chipcie/archive/2022/nwerc/solutions.zip))

**Comment by mpsijm** [comment]
Good catch! :slightly_smiling_face: I think `contest-problem.tex` is only used for the problems that are part of the entire contest PDF, not for the stand-alone `problem.pdf`. So then the remedy to this would be to override `problem.tex` in the NWERC repo, in the same way as how we had overridden `contest{,-web,-problem}.tex`. We just need to remember to do this next time :joy:

**Comment by mzuenni** [comment]
but we also need to change the code, right? At least my attempt to place a `problem.tex` inside the contest directory next to the other override files did not change anything.

**Comment by mpsijm** [comment]
Ah, good point, I thought that this was already a thing, woops :joy:
