### ISSUE TITLE
Suppress `Falling back…` warning when not falling back 

### ISSUE THREAD

**Issue by thorehusfeldt** [RagnarGrootKoerkamp/BAPCtools#253]
If a Python 3 program ends with `.py` and has the proper shebang, it is correctly determined (at priority 902) to be in Python 3. However, before getting there, at priority 900, `bin/program.py`, when unable to find a PyPy2-compiler, issues the unhelpful warning about “falling back” to a lower-priority language.

https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/9bad670a48a8027089b994cc6392a10d53623845/bin/program.py#L198

and setting `fallback` to `True`. The result is something like this:
```
> bt validate -v
PROBLEM blahblah
Build input_format validators: validate.py Compile program pypy not found for language Python 2. Falling back to lower priority languages.
Build input_format validators: validate.py Falling back to Python 3.
```

… when in fact it fell “forward” to a higher-priority language.

The easiest fix for this particular situation is to make Python 3 the default for `.py` in `languages.yaml`.

**Comment by RagnarGrootKoerkamp** [comment]
Yeah so... Python 2 is stil the default language in the spec, and so far we didn't want to break that compatibility.
Problemtools merged [a PR](https://github.com/Kattis/problemtools/pull/197) to default to python 3 into `develop` just this week, but if you want to be compatible with other versions and domjudge and kattis, you should to put the python3 shebang at the top.

(ie, i can fix it in BAPCtools, but it's not going to fix the problem you'll get eventually when uploading the problem.)

**Comment by RagnarGrootKoerkamp** [comment]
To clarify: the priority 902 python requires the shebang to match, as states in the comments at the top of the file

**Comment by thorehusfeldt** [comment]
Forgive me for not being clear.

The issues is *not* about having to add a shebang in Python 3-files. (I’m fine with that and always do that.)

The issue is this that a language with priority $p$ that is rejected in line 198 because the compiler can’t be found leads to a “Falling back…” warning *even if* the `for`-loop later correctly finds a match with priority  $p'>p$, which would have been adopted whether the compiler is present or not. No “falling back” actually takes place.

For an example consider the situation where PyPy does not exist and a `.py` file with a `python3` shebang. It is correctly determined as a Python 3 file *and* emits the warning about falling back (from Python 2 (PyPy), at priority 900) to a *lower priority language* (in fact, Python 3 at priority 902).

**Comment by thorehusfeldt** [comment]
To fix, we’d need to 
1. collect tuples of `(lang, matching_files, priority)`  into a list `candidate_languages`, basically as in the loop from 174-187
2. sort `candidate_languages` by `priority` (not unlike lines 215-220)
3. iterate over `candidate_languages`, discarding candidates with nonexisting compile or run programs, applying the logic in lines 189-213 and break at the first match

**Comment by RagnarGrootKoerkamp** [comment]
Ok, understood and reproduced the issue now. Basically did what you suggested in the comimt above. Let me know if this solves it indeed.

**Comment by thorehusfeldt** [comment]
@RagnarGrootKoerkamp : did this quite work? `lang_conf` in 199 is the configuration of the `lang` of the last iteration of the previous for-loop, no? (I may misunderstand.)

**Comment by RagnarGrootKoerkamp** [comment]
Good catch; thanks for reviewing :) 
Should be fixed now.
