### ISSUE TITLE
`get_testdata_yaml` should also consider `in_path`, not only its parents

### ISSUE THREAD

**Issue by thorehusfeldt** [RagnarGrootKoerkamp/BAPCtools#257]
Unless, I’m confusing myself, a call to `get_testdata_yaml(problem, PurePath("data/secret")` would return the information stored in `data/testdata_yaml`, instead of that in `data/secret/testdata.yaml`.

This is never a problem, because `get_testdata_yaml` seems to be only ever called with `in_path` being the path (in fact, the `short_path`, not the `in_path`, which is a bit confusing) of a _testcase_ (rather than any kind of path into the testdata directory.)

What the method _should_ return is the `testdata.yaml` that is relevant for the given `in_path`. It currently does that only if `in_path` points to a testcase.

https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/d78017df1c21f62020e0ed7433286903cb2f05e3/bin/problem.py#L118

Quick fix is to just prepend `in_path` to the iteration, as in `[in_path] + list(in_path.parents)`. An `in_path` should maybe be `short_path` or just `path`.

**Comment by RagnarGrootKoerkamp** [comment]
Did you already fix this meanwhile? I'm not exactly sure why `get_testdata_yaml(problem, <directory>)` would be needed but sound reasonable to make it work.
