### ISSUE TITLE
Infer testdata settings from ancestors for each key

### ISSUE THREAD

**Issue by thorehusfeldt** [RagnarGrootKoerkamp/BAPCtools#258]
It is my understanding that if `data/secret/testdata.yaml`  exists but does not set key `foo`, then the value of `foo` should be inferred from `data/testdata.yaml`. Unless I’m mistaken, this is not what happens here: 

https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/d78017df1c21f62020e0ed7433286903cb2f05e3/bin/problem.py#L116

The [specification](https://www.kattis.com/problem-package-format/spec/problem_package_format#test-data-groups) is actually on the side of BAPCtools:

> **Test Data Groups**
> […] In each test data group, a file testdata.yaml may be placed to specify how the result of the test data group should be computed. If such a file is not provided for a test data group then the settings for the parent group will be used. 

According to the above quote, we only consult the parent if the _file_ `testdata.yaml` is missing in the current group.

But `verifyproblem` disagrees, see https://github.com/Kattis/problemtools/blob/ea951339966ded5715f5d6f4554ede396eedbb66/problemtools/verifyproblem.py#L322 
```python
        # For non-root groups, missing properties are inherited from the parent group
        if parent:
            for field, parent_value in parent.config.items():
                if not field in self.config:
                    self.config[field] = parent_value
```
I can find no information about whether this inference rule proceeds upwards.

**Comment by RagnarGrootKoerkamp** [comment]
Just FYI: while bapctools supports these, we never use them in bapc/nwerc. So basically support for this is limited. problemtools is used more for scoring problems and such. So such inconsistencies are likely just implementation side effects...

**Comment by thorehusfeldt** [comment]
Yes, I think I understand this. As far as I can tell, BAPCtools restricts its attention to problems that

1. use a testdata hierarchy with 3 exactly internal nodes (`data`, `data/sample`, and `data/secret`.)
2. don’t use `testdata.yaml` to send flags to input or output validators (but sends two flags to output validation under `bt validate -o`).
3. use the default grader with default grading flags. (At least `on_reject: break` seems to be hard-coded.)

There may be other implicit assumptions. But except for a few details, BAPCtools is well designed and is quite easy to fix, I have a fork that verifies problems with deep data hierarchies, and with scoring graders just fine. 

Feel free to close this issue.

**Comment by RagnarGrootKoerkamp** [comment]
I will close this for now since what is implemented aligns with the spec. Problemtools does have inheritance (and maybe kattis also), so we may want to change the spec. In that case this can be reopened.
