### ISSUE TITLE
New parallelism breaks lazy judging

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#270]
We want to stop judging as soon as we hit a `TLE (aborted)` testcase.
This broke in #268 (27daebadea8a0a32ed032f72c08d0dcbe9dd6b53).

cc @mzuenni @mpsijm

**Comment by mzuenni** [comment]
This seems to work for me? @mpsijm do you have an example where it breaks?

**Comment by RagnarGrootKoerkamp** [comment]
For me it also seems to work on BAPC22/lazyparallism. Might have to do with python version or so?

**Comment by mpsijm** [comment]
Funnily enough, it only breaks for me when `--jobs=0`, not when `--jobs=1`. :joy: See #275 for a fix :slightly_smiling_face:
