### ISSUE TITLE
Generators documentation: more accessible terminology

### ISSUE THREAD

**Issue by thorehusfeldt** [RagnarGrootKoerkamp/BAPCtools#286]
(This is not about changing functionality, but using terminology that is more aligned with the terminology used in the problem format specification.)

*Analysis*: Too many things are called `generator(s)` right now: 
1. the entire framework, 
2. the `generators.yaml` file,
3. the _programs_ that generate something (i.e., the values of the fields in `Generators::generators:` in the CUE specification, such as `gen_random.cpp`)  
4. the `generator` objects in the CUE specification and documentation (which can be _invocations_ of generator-programs (called `input` or `command`), paths to “manual” testcases, and strings that explicitly are the contents of '.in'-files), 

This is not easy to understand. I propose to reduce this semantic overlap by being more stringent about the distinction between the entries/keys/field-labels of `Generarators::generators` and those of `generator`. There could be many good words/concepts/constructs for this (`invocation`, `instance-definition`, `generating_programme_path`, etc.), but the specification itself already provides semantic concepts that are close enough. I propose to use those, if only to increase accessibility of the framework.

| Current (Cue object if `monospaced`) | Proposed | What it is |
|--------|--------|--------|
| `generator`  | `testcase` | something (a generator-invocation-command, a path, a string of explicit contents) that specifies a testcase’s `.in`-file,  and possibly other files |
| `directory` | `testgroup` | information about a testgroup, including its testcases, subtestgroups, settings provided  by `testdata.yaml`, and information (visualiser, solution, salt) pertaining to this testgroup and its descenants |
| `generators` | `generators` | a dictionary of programs-that-generate-testcases
| generator | generator | the entries/keys/field-labels in the `generators` object, i.e., a program that _generates_ a testcase

Addressing this issue involves
1. editing the`doc/generators.md`
2. changing the field labels in the CUE specification and JSON schema
3. possibly (but reluctantly) changing some variable names in the source code

**Comment by RagnarGrootKoerkamp** [comment]
I think the names you proposed completely make sense from a user perspective and I agree it makes sense to change that.

My only small worry is that renaming all the classes and such in `generate.py` might confuse myself mostly, but that should be OK in the end. I'm also not happy with this `Rule` name which is a superclass of `TestcaseRule` and `DirectoryRule`.

**Comment by thorehusfeldt** [comment]
The generators specification has changed a lot over the past few weeks, and I’d like to update the CUE schema. I’m happy to make a proper pull request, but maybe we can align expectations first here.

My best current bet is the following, for CUE 0.5:
```cue
package problemformat

// To validate generators.yaml using cue:
// > cue vet generators.yaml *.cue -d "#Generators"

import "struct"

#command: !="" & (=~"^[^{}]*(\\{(name|seed(:[0-9]+)?)\\}[^{}]*)*$")
#file_config: {
	solution?:    #command // null disallowed (specify #testcase.ans instead)
	visualizer?:  #command | null // null means: skip visualisation
	random_salt?: string
}

#testcase: 
	#command |            // same as generate: #command
	{
		generate?: #command // invocation of a generator
		copy?:     #path 
		["in" | "ans" | "desc" | "hint" ]: string // explicit contents
		#file_config
	} 

#data_dict: [string]: #testgroup | #testcase
#data_dict: struct.MinFields(1)                        // nonempty
#singleton_data_dict: #data_dict & struct.MaxFields(1) // exactly one key

#testgroup: {
	"testdata.yaml"?: #testdata_settings        // TODO should this field be called testdata_settings or settings?
	data: #data_dict | [...#singleton_data_dict]
	#file_config
}

#Generators: {
	generators?: [string]: [...string]
	#testgroup
	... // Do allow unknown_key at top level for tooling
} 

#Generators: data: close({
		// Restrict top level data to testgroups 'sample', 'secret'
		sample: #testgroup
		secret: #testgroup
	})
```

Notable changes:
1. the schema uses definitions, indicated with `#`, since “In CUE, schemas are typically written as Definitions.” https://cuelang.org/docs/tutorials/tour/intro/schema/
2. CUE’s Definition objects are by default _closed_, I’ve opened only the `#Generators` object using `...` for inclusion of other keys
3. `testcase` and `testgroup` are new object names, see discussion upthread
4. I’ve explicitly closed toplevel `data` to have exactly two keys (`sample` and `secret`), with must be `testgroup` (and not `testcase`.)
5. data dictionaries are nonempty. (debatable, the [specification](https://www.kattis.com/problem-package-format/spec/problem_package_format#test-data-groups) says » Each test data group may consist of zero or more test cases (i.e., input-answer files) and zero or more subgroups of test data (i.e., subdirectories).«)
6. _lists_ of data dictionaries are now singletons 
7. the schema does not specify that at least one `in`-generating key exists in `testcase`. This is mainly because there is only ugly CUE syntax for this right now, it will be readable in `0.6.0`, which is currently in alpha
8. I’ve invented a  `package problemformat` that specifies `testdata_settings` (and some other things), but doesn’t belong to the generators specification
9. Should `testdata.yaml` be called `settings` or `testdata_settings`? Arguments _pro_: it’s less of a typographical outlier, it doesn’t directly conflict with the `parent.child` naming structure employed by `CUE`, it requires quotes, data formats shouldn’t describe semantics, the contents describe “the settings of the testdata” no the “YAML of the testdata (which might as well be the `generators.yaml`). Arguments _contra_: nobody will ever by confused by it.
