### ISSUE TITLE
add support for VIVA

### ISSUE THREAD

**Issue by godmar** [RagnarGrootKoerkamp/BAPCtools#29]
Hi, my favorite input format validator is [VIVA](http://viva.vanb.org/) which for many problems allows very concise input format validators that meet Kattis/problemtools standards.  In many cases, it entirely eliminates the need for additional input validation before the problem can be approved.
In Kattis problemtools, it recognizes the presence of .viva files in the input_format_validator directory, e.g. [here](https://github.com/acmgnyr/icpc-2014-gny-kattis/blob/master/sequence/input_format_validators/sequence.viva)

Consider using it/adding support for it.

**Comment by RagnarGrootKoerkamp** [comment]
Does that mean this tool already has users outside of BAPC? Awesome!

I've never used VIVA myself before but happy to add it of course. I'll try to play around with it a bit this week.

What would be a correct VIVA file to check for a single integer between 0 and 10^9, followed by a newline? (That's the 'example problem' in the repository so I can add it there for testing.)

**Comment by RagnarGrootKoerkamp** [comment]
Is VIVA typically installed somewhere in $PATH? I see that problemtools only checks the `support` directory, but I'd prefer to not pull VIVA into this repository.

**Comment by godmar** [comment]
No, it's not typically installed as it's specific to programming contests, although you could make that assumption. problemtools keeps a copy of the .jar file in its support directory which is updated infrequently (in fact, the last version of VIVA is 2 years old and runs very stable). 

I consider it a defacto standard, so if BAPCtools aims to validate the widest possible selection of CLICS packages, it ought to support it out of the box. That's just my opinion, obviously.  I personally prefer it to CTD or writing C/C++ code like in Polygon, after having created or helped create probably 100-200 packages.

**Comment by RagnarGrootKoerkamp** [comment]
Well, it's part of the _actual_ standard which I try to follow: https://clics.ecs.baylor.edu/index.php?title=Problem_format#Input_Validators

Given that a jar is all that's needed and it's not updated anyway, including it in the repository SGTM. There's no point in making a paradigm shift and requiring people to install it separately while it already 'just works' with problemtools.

(For CTD on the other hand, building it is complicated enough that I don't like it so much as a direct dependency/submodule of this repository.)

Out of curiosity: What is the main point of VIVA over CTD?

**Comment by RagnarGrootKoerkamp** [comment]
The commit above adds this. Can you maybe test it on some actual problems? I just tested it on single integer input only and that seems to work fine.

**Comment by godmar** [comment]
I'm actually not using bapctools, I use problemtools. I just saw your posting on the problemtools github issue regarding bad input test data, so that's how I learned about bapctools.
You're welcome to use (and include) some packages for unit/system test purposes if you'd like, such as https://icpc.cs.vt.edu/hs/2018/vths-contest-2018.zip or the GNY 2014 I've linked to.

Re: CTD vs. VIVA. CTD is a lot more verbose, viva has lots of conventions that are typical in problem already built-in (spacing, etc.), it's just more concise and mathematical. For some problems, VIVA is also significantly faster than CTD.

One of my visions/wishes for the future is for the English prose in the Input section to be automatically generated from the input validator. VIVA would be a good candidate if one were to start such a project, IMO.

**Comment by RagnarGrootKoerkamp** [comment]
Right, I agree that CTD is slow. That's the reason we created our own (yet another...) c++ header for input validation. This header also supports checking that e.g. the max value of `n` over all testcases is equal to the maximal allowed value of `n`.

BAPCtools can also do regexes on the `problem.en.tex` input section to make manual checking of bounds somewhat easier, but that remains an annoying point. Generating input sections from an input validator sounds cool, but also very difficult to do in practice.
