### ISSUE TITLE
`bt run` always regenerates

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#308]
It should use the cache/metadata to not regenerate up-to-date cases, but this is broken at the moment.

Workaround: do `bt run -G` (aka `bt run --no-generate`).

**Comment by mzuenni** [comment]
fixed with 1f450092b5551ef67eb5750867c3bbfb39600d30

**Comment by RagnarGrootKoerkamp** [comment]
oh lol, I'm to `blame` here :P

Thanks for fixing

**Comment by thorehusfeldt** [comment]
Very smooth experience now!

(Now if only `invalid_inputs` were an alias for `bad` my generating experience would be perfect.)
