### ISSUE TITLE
`bt pdf` should quick-generate samples

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#309]
When samples are fully in `generators/generators.yaml`, `bt pdf` doesn't automatically pick them up. We should make a special case to generate samples as fast as possible, ideally without validating them, nor building all generator.

Until then, it's best to keep samples committed, even if they are generated

**Comment by mzuenni** [comment]
Why do we want to skip validation? For samples we want to be sure that they are valid and it should normally be fast due to caching?

**Comment by RagnarGrootKoerkamp** [comment]
fair enough. I mostly want to avoid that `bt pdf` takes long because it has to build 10 validators. Many times people only work on a single/few problems and don't have build artifacts for everything in the cache, but are interesting in building the full pdf.

Alternatively, we could decide to not `.gitignore` samples and keep them committed for simplicity

**Comment by RagnarGrootKoerkamp** [comment]
I think we settled on committing samples, simplifying this.
That means that when you update samples in `generators.yaml` you should also update the committed samples but that should be fine.
