### ISSUE TITLE
Errors when generating duplicate cases

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#310]
When some cases have the same generator invocation, they have the same hash and hence use the same working directory. That causes problems when generating two such cases in parallel.
Two ways this may be fixed:
- Only generate the first copy of each duplicate case, and let the others copy from the same generated files. (Annoying because those generators have to wait for the first one to finish.)
- Make duplicate generator invocations a fatal error before doing anything else?

cc @mzuenni

**Comment by mpsijm** [comment]
I don't mind the fatal error. We generally don't want duplicate test cases anyway, and it's a good opportunity to teach people about `{seed:X}` in the error message :slightly_smiling_face:

**Comment by mzuenni** [comment]
There are cases where we want duplicate cases, for example if the AC probability on that case is 50% we may want to duplicate it a few times... but in that case the `count` key would be better suited?

**Comment by mpsijm** [comment]
Note that it is not impossible to generate test cases with duplicate _contents_, just the generator invocations need to be distinct. I do agree that this is a bit unwieldy until we implement a `count` (#271) :stuck_out_tongue: But having to deal with duplicate hashes is also annoying :upside_down_face:

**Comment by RagnarGrootKoerkamp** [comment]
I think we can just make it a fatal error for now and revisit later.

Some places anyway advocate that submissions must be deterministic so then duplicate inputs make even less sense.

Another case where duplicate inputs are useful is with test groups with different output validation flags, but in that case `include:` is better and duplicate commands are't needed either.

Also note that `count:` would not actually generate bit-identical testcases since it uses a different seed each time. What this issue is about is where the exact same command is run with the same seed.
