### ISSUE TITLE
generators.yaml: Allow `testcase.in: <input>` shortcut

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#316]
It would be quite convenient to make
```
testcase.in: <input>
```
a shortcut for
```
testcase:
  in: <input>
```

This would make specifying such testcases quite a bit cleaner since it removes one line and one indentation level per case, making things quite a bit more compact. In particular in cases where previously `stdout.py` was used the new syntax is quite a bit more verbose.

This is similar to how
```
testcase: <command>
```
is a shortcut for
```
testcase:
  generate: <command>
```

This somewhat breaks the 'uniqueness of testcase names' check, but on the other hand that is already broken since you can already write
```
data:
  - testcase: ...
  - testcase: ...
```

@mpsijm @mzuenni @thorehusfeldt wdyt?

Note that such shortcuts only make sense for keys under `testcase:` that generate input, since only generating an answer doesn't make sense. The only other key for which this could make sense is `copy: manual/testcase`, so we could also add `testcase.copy: manual/testcase`, but I'm not quite sure I like that as much and anyway `copy:` is much less used.

**Comment by mzuenni** [comment]
i am a fan of making `copy` and `in` less verbose and single liners... but i am not sure if i like that its done by adding `.xyz` to the name of the testcase... any idea for another syntax that is yaml compatible?

**Comment by thorehusfeldt** [comment]
We can to

```yaml
mytestcase: { in: foo bar }
```

and I can see from my current repo that I use that quite a lot. For me, that’s sufficient.

**Comment by RagnarGrootKoerkamp** [comment]
yes all JSON is also valid YAML. But for multiline input it's ugly as you need to do
```
testcase: { in: 'foo\nbar' }
```
where
```
testcase.in: |
  foo
  bar
```

would be nicer to read.

**Comment by thorehusfeldt** [comment]
Got you. I don’t think it’s worth it; the parts where I have multiline remain multiline even with the new syntax; and the parts where I want single-line for overview I can get with flow style.

**Comment by mzuenni** [comment]
I see that it feels natural but on the other hand i don't want to end up with three different Syntaxis for `copy`, `generate` and `in`

**Comment by RagnarGrootKoerkamp** [comment]
ok, I'll close this for now :)
