### ISSUE TITLE
Write generated .gitignore file before generating

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#317]
That way things are even ignored if the generate command is aborted halfway through

**Comment by mzuenni** [comment]
I think we want to ignore the whole data (or only secret?) directory instead of ignoring testcases?

**Comment by RagnarGrootKoerkamp** [comment]
True; I think I'm currently leaning towards letting the user ignore all data or all data/secret directories as they wish and just drop this (kinda complex) feature anyway.
