### ISSUE TITLE
input format validator: Any non-42 exit is a fail, not just 43.

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#318]
I think we currently want exit code 43, but a crash in the validator is also OK.

E.g. if you do `n = int(input())` in python that crashes for non-int input, and that's OK.

See also https://icpc.io/problem-package-format/spec/problem_package_format#exit-codes

**Comment by mzuenni** [comment]
if we allow this it gets harder to find actual errors in the checker?

**Comment by RagnarGrootKoerkamp** [comment]
Well, this is what the spec says. Also I don't think that's much of a problem. Correct inputs still need to completely pass anyway. The only difference is that input validators could now crash on bad inputs instead of reporting nicely they're wrong, but that's ok imo.

**Comment by thorehusfeldt** [comment]
In particular, it allows

```python
assert 1 <= n <= m, "foo"
```
instead of
```
if not 1 <= n <= m:
    fail("foo")
```
