### ISSUE TITLE
Export all `data/secret/**/*.in`, not just `data/secret/*.in` in `bt export --kattis`

### ISSUE THREAD

**Issue by thorehusfeldt** [RagnarGrootKoerkamp/BAPCtools#321]
This:

https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/567fbbf8a4ebe10b632a11a4f113dcd4d4909463/bin/export.py#L112

should just be `data/secret/**/*.in`, and similarly (but less critically) for `data/sample`.

(Genuine question: should not `.hint`, `.desc`,  and various image be exported as well?)

**Comment by RagnarGrootKoerkamp** [comment]
Hmm indeed it looks like we didn't export visualizations at all, thanks for noticing :)
