### ISSUE TITLE
Distinguish output validation from `.ans`-validation

### ISSUE THREAD

**Issue by thorehusfeldt** [RagnarGrootKoerkamp/BAPCtools#324]
BAPC includes an excellent routine for checking the validity of `.ans`-files with the same case as `.in`-files.

This does, however, lead to two problems
1. incompatibility with “the specification” and other tools, which neither expect or allow the presence of, say, an extra output validator when `validation:default`. 
2. inaccessible documentation and workflows; I can only speak for myself, but it took me a long time to wrap my head around the logic now sketched in https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/master/doc/validation.md#output-validation 

I suggest to conceptually distinguish between the validation of `data/**/.ans` (which I refer to as _default answers_, here just _answers_) and the output of a submission (which I refer to as _submission output_, here just _output_). The former is a constraint on the problem designer, the latter is a correctness requirement on the solver’s submission.

There are many ways of cutting the cake, but to get the ball rolling, I propose

```
<problem_name>/answer_validators
```

The semantics are like `input_validators`. (In particular, there can be more than one program in that directory, all of which have to pass on all `.ans` files.) A validator in this directory might also have access to `testcase.in` and `testcase.ans`.

**Comment by RagnarGrootKoerkamp** [comment]
I really like this idea. It would remove a lot of confusion and clearly indicate that this is something outside the spec.

So we could easily already accept `answer_validators` and map that to what is currently internally called `output format validators` (but that can then be renamed to just `answer validators` :) ).

More tricky is what happens with existing `output_validators/`:
1. For default-output-validation problems: we can suggest (`log`) to rename this to `answer_validators`, and continue to use them as usual.
2. For custom-output-validation problems, the output validator is currently used for two things:
  a. Validate team output, as in the spec.

**Comment by RagnarGrootKoerkamp** [comment]
CC @mpsijm @mzuenni

**Comment by mpsijm** [comment]
Sounds like a good idea to separate out-of-spec output format validation from the in-spec custom `output_validator` :slightly_smiling_face: 

Regarding the naming, why not `output_format_validators`, if that's already how we call it internally? It's also consistent with what used to be called `input_format_validators` in the spec (this is now simply called `input_validators`, plus I like the fact that this keeps the directories together in alphabetical order. :innocent:

**Comment by RagnarGrootKoerkamp** [comment]
I agree that having them close in alphabetical order is nice, but really we want to validate the `.ans` files, not the format of whatever the teams output. And also `input format validators` doesn't actually occur in the spec anymore I think, so it's nice to have symmetry between testcase `input`, `answer`, `output` and `{input,answer,output}_validators/`.

**Comment by mpsijm** [comment]
All right, makes sense! As long as it's clear that there is a distinction between "output" and "answer" (because I expect that new people might think they mean the same), I'm fine with `answer_validators` :slightly_smiling_face:

**Comment by thorehusfeldt** [comment]
For precision, consider  `default_answer_validators`, `ans_validators`. I like neither of these. (For instance, there is also a default output validator, which is none of these things.)

**Comment by mzuenni** [comment]
How are `answer_validator` invoked now?
@RagnarGrootKoerkamp  proposed 
`answer_validator /path/to/testcase.in < /path/to/testcase.ans`
instead of the previous
`output_format_validator /path/to/testcase.in /path/to/testcase.ans < /path/to/testcase.ans`

However, the second option makes it easier to reuse the `output_validator` as `answer_validator` (like bapctools did before)?

**Comment by thorehusfeldt** [comment]
Believe it or not, the documentation in my PR is quite up to date: https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/b30fbc4150e0cbec9855325d741ed370fe44e455/doc/validation.md 

It is as you say. In summary,

```
inval [flags] < case.in
ansval case.in [flags] < case.ans
outval case.in case.ans tmpdir [flags] < case.ans
outval case.in case.ans tmpdir [flags] < submissionoutput
```

`bt validate` answer-validates all `.ans` and _also_ subjects them to the output validator using the third format above.

**Comment by thorehusfeldt** [comment]
Currently we aren’t sending `case_sensitive` and `space_change_sensitive`. @RagnarGrootKoerkamp  and I did discuss this, and didn’t really discover very strong argument either way.

Note that if `validation: default` then it makes no sense anyway (the `.ans` file is compared against itself).

So the interesting case is when Alice has written her own output validator. But then the BAPC High Wardens of Problem Quality want to incentivise her to write an explicit output validator anyway instead of falling back on a tempting (and effort-saving) default.

I have no opinion.
