### ISSUE TITLE
Warn if \problemtitle differs from problem.settings.name[language]

### ISSUE THREAD

**Issue by thorehusfeldt** [RagnarGrootKoerkamp/BAPCtools#326]
When `problem.en.tex` contains
```tex
\problemname{Hello Gaia!}
```
but `problem.yaml` contains
```
name:
  en: Hello World!
```
there currently is no warning. BAPC instead expects the author to write
```tex
\problemname{\problemyamlname}
```
but there can be reasons to avoid that macro, typically due to other tooling. (In particular, it is one of the few details that prevents a BAPC-compatible problem package from being `problemtools/verifyproblem`-ed.)

There is extensive parsing of TeX-code already being done in `bt constraints`, but the above check could be done quite easily and catch 99% of cases.

A more aggressive solution would be to actually edit `problem.en.tex` after `bt new_problem` and `bt rename_problem`.

**Comment by RagnarGrootKoerkamp** [comment]
Sounds reasonable to add a warning/log for this indeed.

I think the most common usecase for this is when the latex name includes additional markup that we don't want to expose in the yaml. But it's probably fine to just warn for these cases anyway since accidental mismatches are worse than a few extra warnings.

**Comment by mzuenni** [comment]
We could also check if the expected string is a substring of the actual string... That would reduce the number of warnings but would also suppress the warning for some types of typos.

**Comment by mzuenni** [comment]
It would not war for markup like this: `\texttt{IX}th Problem` because `IXth Problem` is still a substring. On the other hand it would no longer warn for `IXth Poblem` or stuff like that...

**Comment by thorehusfeldt** [comment]
Ah, _that_ kind of substring. Now it makes sense.

**Comment by thorehusfeldt** [comment]
Minimal solution is now a concrete pull request, please comment there.
