### ISSUE TITLE
Update problem skeleton

### ISSUE THREAD

**Issue by thorehusfeldt** [RagnarGrootKoerkamp/BAPCtools#332]
The problem skeleton in `/skel` is getting a bit long in the tooth. Here are some issues:

1. Problem name in `problem.yaml` is not longer up to date with multilingual problem title support: https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/689d1ab993ead6ab7b4c1a91f718708bc0c81e8f/skel/problem/problem.yaml#L1
2. There should be no `data` directory
3. `generators/stdout.py` is obsolete. A good small _random_ generator in python (taking seed) would make sense as an example instead.
4. the `generators/generator/` symlink should just be removed.
5. `generators/generator.yaml` should contain an `invalid` input.
6. there should be an `answer_validators` (presumably filled with just the old `output_validators`

There may be more.

**Comment by mpsijm** [comment]
RE point 6: the skeleton `answer_validators/answer_validator/answer_validator.cpp` can contain slightly less code than the current `output_validator.cpp` does.

Additionally, as I mentioned in https://github.com/RagnarGrootKoerkamp/BAPCtools/pull/330#discussion_r1461118557, it's probably best to remove the `output_validators` folder in case `validation: default`.

**Comment by RagnarGrootKoerkamp** [comment]
Agreed on all points.
7. Additionally, maybe we can drop the `validate.{ctd,viva}.template`, or at least not copy them in by default. they're just noise. Probably the same for `submissions/accepted/name.cpp.template`.

**Comment by thorehusfeldt** [comment]
8. The C++ object in the new `answer_validators/answer_validator` should be of class `AnswerValidator` (rather than just the `OutputValidator` from the retired `output_validators` directory.)

**Comment by mzuenni** [comment]
also see #303
