### ISSUE TITLE
BAPCtools user :wave: 

### ISSUE THREAD

**Issue by byorgey** [RagnarGrootKoerkamp/BAPCtools#350]
Hi there, as requested, just letting you know that I'm using `BAPCtools` to help develop the problems for https://hendrix-cs.github.io/hcpc/ .

Do you have any experience/hints/advice for setting up `BAPCtools` to run in GitHub Actions?  I'd love to set up CI for my repo so that it runs `bt all`.

**Comment by RagnarGrootKoerkamp** [comment]
Hey, great to hear from you!

So far we've been using gitlab CI mostly, and `bt gitlabci` can automatically generate a `.gitlab-ci.yml` file for it that detects changes and only reruns for problems with changes. I haven't used github CI much so don't know if this can be ported.

There is the `ragnargrootkoerkamp/bapctools` docker container containing BAPCtools and commonly used programming languages that we use in gitlab so a single thing to do would be to reuse that and simply run `bt all` in the problems directory.

Also, let us know if you run into unclear documentation. We've been rewriting a lot recently and docs aren't always fully up to date.
