### ISSUE TITLE
Required python version

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#388]
The readme says we require 3.6, but it seems we now use a bunch of `match` statements that require 3.10.

**Comment by mpsijm** [comment]
Already fixed in https://github.com/mpsijm/BAPCtools/commit/f33fcd5ebea51966c83fbd2ba0f615b0dc57ca3b, but I'm not done fixing all type errors yet :stuck_out_tongue:

**Comment by RagnarGrootKoerkamp** [comment]
If you plan on merging that within the next ~month, that's fine.
