### ISSUE TITLE
Parse `n\in \{1, \dots 10\}` from statement as part of constraints checking

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#396]
More general pattern could be something like
```
<var> \in \{<low>, \.?dots, <high>\}
```

**Comment by thorehusfeldt** [comment]
In fact, one of the typical situations where I (as a mathematician) strongly prefer the set notation, is

> each of which contains the position _x_, _y_ ∈ {12, …, 17} of the _i_th stroopwafel

So `<var>` might be `<var> (, <var>)`.

Compare this to Dutch style:

> each of which contains two integers _x_ and _y_ (12 ≤ x, y ≤ 17), the position of the _i_th stroopwafel  

which is longer (integers are implicit in the set enumeration), and can be misunderstood in at least two ways (as two separate constraints 12 ≤ x and y ≤ 17, and actually containing three values (_x_, _y_, and a position).

**Comment by thorehusfeldt** [comment]
Note sure if the easiest implementation is just it `constraints:constraint` to rewrite such expressions as  `lo <= x <= hi`.

**Comment by thorehusfeldt** [comment]
Maybe the following transformation is enough, possibly at constraints.constraint:83: 
```python3
    if m := re.match(r"(.*)\\in.*\\{(.*,.*\\[lc]?dots.*,.*)\\}", text):
        variables, intrange = m.groups()
        lo, _, hi = intrange.split(",")
        print(f"{lo} <= {variables} <= {hi}")
  ```
  
  Test with 
  
  ```
 import re

for text in [
        "x\in\{1,\ldots, 5\}",
        "x\in\{1,\dots, 5\}",
        "x\in\{1,\cdots, 5\}",
        "x\in\{1,  \ldots,5\}",
        "x,y, a_i\in\{1,  \ldots,5\}",
             ]:
    if m := re.match(r"(.*)\\in.*\\{(.*,.*\\[lc]?dots.*,.*)\\}", text):
        variables, intrange = m.groups()
        lo, _, hi = intrange.split(",")
        print(f"{lo} <= {variables} <= {hi}")
  ```
