### ISSUE TITLE
Move generators JSON-schema from schemastore to this repo

### ISSUE THREAD

**Issue by thorehusfeldt** [RagnarGrootKoerkamp/BAPCtools#405]
Currently, there exists at https://github.com/SchemaStore/schemastore a JSON schema that validates `generators.yaml` automatically from editors that support this.

* The JSON schema: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/problem_package_generators.json
* Positive tests: https://github.com/SchemaStore/schemastore/tree/master/src/test/problem_package_generators
* Negative tests: https://github.com/SchemaStore/schemastore/tree/master/src/negative_test/problem_package_generators

This schema should instead be hosted directly in the BAPCtools repo, possibly at `support/schemas`.

To this end,

1. Follow the steps under  https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md#how-to-move-a-json-schema-from-schemastore-to-somewhere-thats-self-hosted
2. Move the `.json` file to `support/schemas` and the content of the two test directories to `test/`, in fact maybe to `test/generator_yaml`.

Questions: 

Q1: should we finally introduce some sort of versioning, so the CUE, YAML, JSON and prose specifications of `generators.yaml` can refer to each other? The schemastore expects our schemas to have version numbers; see, e.g., the format for referring to our locally hosted version: https://github.com/SchemaStore/schemastore/pull/2421/files . Thus, some kind of decision needs to be made. I unanimously decided that the schema currently at schemastore represents version 0.9 of the generators framework. Possible names for the post-migration version could be 0.9.1 or 1.0.

Q2: schemastore validates the JSON schema against the test using a javascript validator. We have no such infrastructure. Do we want to automate this?

**Comment by thorehusfeldt** [comment]
More TODO: the page https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/master/doc/generators.md contains two dead links (“here”) to schemata.

**Comment by RagnarGrootKoerkamp** [comment]
Q1. I think I'm OK with making what we have version 1. I don't think we have any planned open feature requests for `generators.yaml` syntax at the moment.

Q2. If it's easy, sure we can add some test infra for this. But I'd also be OK to just run this manually whenever the schema changes, as long as we have some clear instructions on how to run it manually. (But by that point, it's probably easy to copy that into CI as well.)

**Comment by mpsijm** [comment]
Q1: echoing the conclusion from our Slack discussion: let's use `yyyy-mm` version numbers, which is consistent with the problem package format 🙂

**Comment by thorehusfeldt** [comment]
I submitted a pull request to the schemastore, not sure I understand everything.

https://github.com/SchemaStore/schemastore/pull/4207

**Comment by RagnarGrootKoerkamp** [comment]
Yes, this sounds quite reasonable. For a temporary directory we can use `mktemp -d`.
(We could move it to python and into `bt` but I don't think that's really needed.)

**Comment by mpsijm** [comment]
From https://github.com/RagnarGrootKoerkamp/BAPCtools/issues/405#issuecomment-2469791419:

> `TODO` Reestablish testing of the JSON schemata, now use the already-existing (in CI) cue framework.

Since that's done in #410, I assume this can be closed :smile:
