### ISSUE TITLE
`contest.<lang>.pdf` symlinks to `/tmp/.../contest.pdf`, breaking i18n

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [RagnarGrootKoerkamp/BAPCtools#406]
We should rename the generated `/tmp/.../<contest>/latex/contest.pdf` to include the language, and then symlink there.

For problems it does work, as they link
```
problem.<lang>.pdf -> /tmp/.../<problem>/latex/<lang>/problem.pdf
```

**Comment by mzuenni** [comment]
I think 45b585b is sufficient to fix this
