### ISSUE TITLE
Document Python >= 3.6

### ISSUE THREAD

**Issue by jbransen** [RagnarGrootKoerkamp/BAPCtools#69]
The docs says that Python 3 is required, but given that f-string formatting is used it seems that at least 3.6 is necessary. Would be nice to make this explicit in the docs.

**Comment by RagnarGrootKoerkamp** [comment]
Are you aware of any OSes not having python 3.6 already?
(Not that I'd like to backport to 3.5, since I'm using f-strings all over the place, but would be good to know.)

**Comment by jbransen** [comment]
Python 3.5 is available for many OSs, and happened to be installed on my Windows 10, but is also default for example on Ubuntu 16.04
