### ISSUE TITLE
Dockerfile: Add Java 11

### ISSUE THREAD

**Issue by mpsijm** [RagnarGrootKoerkamp/BAPCtools#95]
Most contests use Java 11 instead of Java 8 now, so this can be part of the Docker image as well.

The easiest way would be to just replace `jdk8-openjdk` with `jdk11-openjdk`, I'm just not sure if you'd _also_ want to have Java 8 available (similar to Python 2 vs. 3). However, for Python, the binaries have different names (`python` vs. `python3`); but for Java, they're all named `java`, so I'm not sure you would implement the switching between Java versions. But if you think we don't need to keep Java 8, then we don't need to think about this either :stuck_out_tongue:

**Comment by RagnarGrootKoerkamp** [comment]
I don't know about java backwards compatibility, but only having the latest SGTM.
